config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root"pages#home"
  get "about", to: "pages#about"
  resources :articles

  get 'signup', to: 'users#new'
  post 'users', to: 'users#create'
  resources :users, except: [:new]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :categories, except:[:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    belongs_to :user
    validates :title, presence: true, length: {minimum: 10, maximum: 25}
    validates :description, presence: true, length: {minimum: 10, maximum: 400}
    validates :user_id, presence: true
end

app/models/category.rb
class Category < ApplicationRecord
    validates :name, presence: true, length: {minimum: 3, maximum:25}, uniqueness: true

end 

app/models/user.rb
class User < ApplicationRecord
    has_many :articles, dependent: :destroy
    before_save { self.email= email.downcase}
    validates :username, uniqueness:{case_sensitive: false}, presence: true, 
    length: {minimum: 3, maximum:20}
    VALID_EMAIL_REGEX= /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, length: {maximum: 105},
    uniqueness:{case_sensitive: false}, 
    format: {with: VALID_EMAIL_REGEX}

    has_secure_password
end 

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user, :logged_in?
    def current_user
        @current_user ||= User.find(session[:user_id]) if session[:user_id] 
    end 

    def logged_in?
        !!current_user
        # in rails !! means you are turing a method to boolean
    end 

    def require_user
        if !logged_in?
            flash[:danger] = "You must logged in to perform that action"
            redirect_to login_path
        end 
    end 
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    before_action :set_article, only: [:show, :edit, :update, :destroy]
    before_action :require_user, except: [:show, :index]
    before_action :require_same_user, only: [:edit, :update, :destroy]
    def index 
        @article= Article.paginate(page: params[:page], per_page: 3)
    end 
    # creating new Article 
    def new
        @article = Article.new
    end  

    # showing the Article created
    def show
    end 
    # editing the Article 
    def edit 
        @article = Article.find(params[:id])
    end 
    # deleting an Article 
    def destroy
        @article.destroy
        flash[:danger]= "Article was successfuly deleted!"
        redirect_to articles_path
    end 
    def update 
        if @article.update(article_params)
            flash[:success]= "The Article was successfuly Updated!"
            redirect_to article_path(@article)
        else
            render 'edit'
        end 
    end 

    # creating an Article 
    def create
        @article = Article.new(article_params)
        @article.user= current_user
        if  @article.save
            flash[:success]= "A New Article was created!"
            redirect_to article_path(@article)
        else
            render 'new'
        end 
    end 

    private
    def article_params
        params.require(:article).permit(:title, :description)
    end 

    private
    def set_article
        @article = Article.find(params[:id])
    end 

    def require_same_user
        if current_user != @article.user && !current_user.admin?
            flash[:danger] = "You can only edit or delete your own article"
            redirect_to @article
        end 
    end 

end 

app/controllers/categories_controller.rb
class CategoriesController <ApplicationController
    before_action :require_admin, except: [:index, :show]

    def new
        @category = Category.new
    end 

    def create
        @category= Category.new(category_params)
        if @category.save 
            flash[:success] = "Category has been created"
            redirect_to @category
        else 
            render 'new'
        end 
    end 

    def index
        @categories= Category.paginate(page: params[:page], per_page:3)
    end 

    def show
        @category= Category.find(params[:id])
    end 

    private 
    def category_params
        params.require(:category).permit(:name)
    end 

    def require_admin
       if !(logged_in? && current_user.admin?)
            flash[:danger] = "Only Admin can perform that action"
            redirect_to categories_path
       end 
    end 
end 

app/controllers/pages_controller.rb
class PagesController < ApplicationController 

    def home
        redirect_to articles_path if logged_in?
    end

    def about

    end 

end 

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def new
    end 

    def create
        user= User.find_by(email: params[:session][:email].downcase)
        if user && user.authenticate(params[:session][:password])
            session[:user_id]= user.id
            flash[:success]="You have successfuly loged in"
            redirect_to user_path(user)
            
        else 
            flash.now[:danger]= "Incorrect username or password"
            render 'new'
        end 
    end 

    def destroy
        session[:user_id]= nil
        flash[:success]="You have loged out"
        redirect_to root_path
    end 
end 

app/controllers/users_controller.rb
class UsersController < ApplicationController

    before_action :set_user, only:[:show, :edit, :update, :destroy] 
    before_action :require_user, only: [:edit, :update]
    before_action :require_same_user, only: [:edit, :update,:destroy]
    def index
        @users= User.paginate(page: params[:page], per_page:3)
    end 
    def new 
        @user= User.new
    end 

    def create
        @user= User.new(user_params)
        if @user.save
            session[:user_id]= @user.id
            flash[:success]= "Welcome to the Alpha blog #{@user.username}"
            redirect_to articles_path
        else
            render 'new'
        end
    end 

    def destroy
        @user.destroy
        session[:user_id] =  nil if @user == current_user
        flash[:danger] = "Account and the Articles assocated were deleted"
        redirect_to articles_path
    end 


    def edit 
    end 

    def update
        if @user.update(user_params)
            flash[:success]="your account was updated successfuly"
            redirect_to articles_path
        else
            return 'edit'
        end 
    end 
    def show
        @user_articles = @user.articles.paginate(page: params[:page], per_page:3)
    end 
    private
    def user_params
        params.require(:user).permit(:username, :email, :password)
    end 

    def set_user
        @user = User.find(params[:id])
    end 

    def require_same_user
        if current_user != @user && !current_user.admin?
            flash[:warning] = "you can only edit or delete your own account"
            redirect_to @user
        end 
    end 


end 

app/helpers/application_helper.rb
module ApplicationHelper
    def gravatar_for(user, options={size: 80})
        gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
        size= options[:size]
        gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
        image_tag(gravatar_url, alt: user.username, class: "img-circle")
    end 

  

   
end

app/views/articles/_article.html.erb
<% obj.each do |article|%>
    <div class="row">
      <div class="col-sm-8 offset-sm-3">
        <div class="card">
            <div class="article-title">
                <%=link_to article.title, article_path(article) %>
            </div>
        <div class="article-body">
             <%= truncate(article.description, length: 100) %>
             <div class="article-meta-details">
                <small> created by: <%= article.user.username if article.user%>,
                        <%= time_ago_in_words(article.created_at)%> ago
                        last updated: <%= time_ago_in_words(article.updated_at)%> ago
                </small>
            </div>
        </div>
            <div class="center article-actions">
                <%=link_to "view", article_path(article), class: "btn btn-primary btn-xs"%>
                <%if logged_in? && (article.user == current_user || current_user.admin?)%>
                    <%= link_to "Edit this Article", edit_article_path(article), class: "btn btn-xs btn-primary"%>
                    <%= link_to "Delete Article", article_path(article),class:"btn btn-xs btn-danger", method: :delete, data:{confirm: "Are you sure you want to delete this article?"} %>
                <% end %>
            </div>
         </div>
        </div>
    </div>  
    
<% end %>

app/views/articles/_form.html.erb
<%=render 'shared/errors', obj: @article%>

<div class= "row">
    <div class="col-md-12">
        <%= form_for @article do |f| %>

            <div class="form-group row">
                <div class="col-sm-2 col-form-label">
                     <%= f.label :title %>
                </div>
                <div class="col-sm-8">
                     <%= f.text_field :title, class: "form-control", placeholder: "Article Title", autuofocus: true%>
                </div>
            </div>


            <div class="form-group row">
                <div class="col-sm-2 col-form-label">
                    <%= f.label :description%>
                </div>
                <div class="col-sm-8">
                     <%= f.text_area :description, class: "form-control", rows:10, placeholder: "Body of Artilce", autuofocus:true%>
                <div>
            </div>
            <br>
            <div class="form-group row">
                <div class="col-sm-10">
                    <%= f.submit class:"btn btn-primary btn-lg"%>
                </div>
            </div>

        <% end %>    
        <div class=" center col-xs-4 col-xs-offset-4">
            [ <%= link_to "Cancel request and return to articles listing", articles_path%> ]
        </div>
    </div>
</div>

app/views/articles/edit.html.erb
<h1 align= "center">Edit Article</h1>

<%= render 'form'%>

app/views/articles/index.html.erb
<h1 align="center">Showing All Articles!</h1>
<div class="pagination-wrapper">
    <%= will_paginate @article%>
</div>
<%= render 'article', obj: @article%>

<div class="pagination-wrapper">
    <%= will_paginate @article%>
</div>

app/views/articles/new.html.erb
<h1 align="center">Create New Article</h1>

<%= render 'form'%>

app/views/articles/show.html.erb
<h2 align="center"> Title:<%= @article.title%></h2>
    
<div class ="well col-sm-8 offset-sm-2">
    <ul class="listing">
        <div class="row">
            <div class="center col-md-4 col-md-offset-4">
                 <li>created by: </li>
                <li> <%= link_to gravatar_for(@article.user), user_path(@article.user)%></li>
                <li class="article-title"><%= link_to @article.user.username, user_path(@article.user)%></li>
                <li> <small> <%= pluralize(@article.user.articles.count, "article") if @article.user.articles%></small></li>
            </div>
        </div>
    </ul>

    <h4 class="center"><strong>Description:</strong></h4>
        <hr>
            <%= simple_format(@article.description)%>
</div>
<div class="center article-actions">
    <% if logged_in? && (@article.user== current_user || current_user.admin?)%>
            <%= link_to "Edit this Article", edit_article_path(@article), class: "btn btn-xs btn-primary"%>
            <%= link_to "Delete Article", article_path(@article),class:"btn btn-xs btn-danger", method: :delete, data:{confirm: "Are you sure you want to delete this article?"} %>
            <%= link_to "View all Articles", articles_path, class: "btn btn-xs btn-success"%>
        <% end %>
</div>

app/views/categories/_form.html.erb
<%=render 'shared/errors', obj: @category%>

<div class= "row">
    <div class="col-md-12">
        <%= form_for @category do |f| %>
          <div class="form-group row">
            <div class="col-sm-2 col-form-label"><%= f.label :name,"Category Name"%></div>
            <div class="col-sm-8">
              <%= f.text_field :name, class: "form-control", placeholder: "enter a name", autuofocus: true%>
            </div>
          </div> 

            <br>
            <div class="form-group row">
            <div class="col-sm-12 center">
                <%= f.submit class:"btn btn-primary btn-lg"%>
            </div>
        </div>

        <% end %>    
    </div>
</div>

app/views/categories/index.html.erb
<h1 align="center">Showing All Categories!</h1>
<div class="pagination-wrapper">
    <%= will_paginate @categories%>
</div>
    <% @categories.each do |category|%>
        <div class="row">
        <div class="col-sm-4 offset-sm-3">
            <div class="card">
                <div class="article-title">
                    <%=link_to category.name, category_path(category) %>
                </div>
            <div class="article-body">
                    <small> 
                    <%= time_ago_in_words(category.created_at)%> ago
                    last updated: <%= time_ago_in_words(category.updated_at)%> ago
                    </small>
                </div>
            </div>
        </div>
        </div>  
    <% end %>
<div class="pagination-wrapper">
    <%= will_paginate @categories%>
</div>

app/views/categories/new.html.erb
<h1 align="center"> Create a new Category </h1>
<%= render 'form'%>

app/views/categories/show.html.erb
<h1 align="center"> Category: <%= @category.name%>'s page </h1>

app/views/layouts/_footer.html.erb
<div class="container">
    <footer class="footer"
        <small>
            Copyright &copy; <a href="https://www.udemy.com"> Ruby Practice Course</a>
            by: khalil Frough
        </small>
        <nav>
            <ul>
                <li><%= link_to "About", about_path%></li>
            </ul>
         </nav>
    </footer>
</div>

app/views/layouts/_messages.html.erb
<div class="row">
  <div class="col-sm-8 offset-sm-2 col-sm-offset-2">
    <%flash.each do |name, msg|%>
      <div class= 'alert alert-<%="#{name}" %>'>
        <a href="#" class="close" data-dismiss="alert"> &#215;</a>
        <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String)%>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%=link_to "Alpha blog", root_path, class: "navbar-brand", id: "logo"%>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%=link_to "Home", root_path, class: "nav-link"%>
      </li>
      <li class="nav-item">
        <%= link_to "Articles", articles_path, class: "nav-link"%>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Actions
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
        <%if logged_in?%>
          <%= link_to "New Artilce", new_article_path, class: "dropdown-item"%>
        <%end%>
          <a class="dropdown-item" href="#"><%=link_to "All Users", users_path, class: "dropdown-item"%></a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>


      <!-- beginning of catagories section-->
      <li class="nav-item dropdown">
      <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Catagories
      </a>
      <div class="dropdown-menu" aria-labelledby="navbarDropdown">
      <%if logged_in? && current_user.admin?%>
        <%= link_to "create new category", new_category_path, class: "dropdown-item"%>
      <%end%>
        <a class="dropdown-item" href="#"><%=link_to "Categories", categories_path, class: "dropdown-item"%></a>
      </div>
    </li>


      <!-- end of catagories section-->
  
      <% if logged_in? %>
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <%=link_to 'Logout', logout_path, method:  :delete, class: "nav-link"%>
          </li>
          <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <%="Admin" if current_user.admin?%> <%=current_user.username%>
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <%= link_to "View Profile", user_path(current_user), class: "dropdown-item"%>
          <%= link_to "Edit Profile", edit_user_path(current_user), class: "dropdown-item"%>
          <%= link_to "Delete Profile", user_path(current_user), class: "dropdown-item text-danger", method: :delete, data: {confirm: "Are you SURE?"}%>
        </div>
      </li> <!-- end of dropdown-->
        </ul>
        <%else%>
        <li class="nav-item">
           <%= link_to "log in", login_path, class: "nav-link"%>
        </li>
        <li class="nav-item">
        <%= link_to "Sign up", signup_path, class: "nav-link"%>
     </li>
      <% end %>
      
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
   
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NewProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <%= render 'layouts/navbar'%>
      <%= render 'layouts/messages'%>
     
      <div class= "container">
        <%= yield %>
      </div>
      <%= render'layouts/footer'%>
      <%= debug(params) if Rails.env.development? %>
  
  </body>
</html>

app/views/pages/about.html.erb
<div class="jumbotron">
    <h1 class="center">About Us</h1>
</div>

app/views/pages/home.html.erb
<div class="center jumbotron">
  <h1>ALPHA BLOG</h1>
<%= link_to "Sign Up Now", signup_path, class: "btn btn-primary btn-lg"%>
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any?%>
<div class="row">
    <div class="col-sm-8 offset-sm-2 col-sm-offset-2">
        <div class="alert alert-danger" role="alert">
            <div class="alert-heading">
                <h2 class="alert-title">
                    <%=pluralize(obj.errors.count, "error")%>
                    prohibited this article from being saved:
                    </h2>
                    <div class="alert-body">
                    <ul>
                        <% obj.errors.full_messages.each do |msg|%>
                            <li> <%= msg%></li>
                        <% end %>
                    </ul>
                </div>
                </div>
            </div>
        </div>
    </div>        
<% end %>

app/views/users/_form.html.erb
<%=render 'shared/errors', obj: @user%>

<div class= "row">
    <div class="col-md-12">
        <%= form_for @user do |f| %>
          <div class="form-group row">
            <div class="col-sm-2 col-form-label"><%= f.label :username%></div>
            <div class="col-sm-8">
              <%= f.text_field :username, class: "form-control", placeholder: "Username", autuofocus: true%>
            </div>
          </div> 

      <!--second--> 
          <div class="form-group row">
              <div class="col-sm-2 col-form-label"><%= f.label :email%></div>
            <div class="col-sm-8">
              <%= f.email_field :email, class: "form-control", placeholder: "Enter email", autuofocus: true%>
            </div>
          </div> 
      <!--end of second--> 
      <!--thrid--> 
        <div class="form-group row">
            <div class="col-sm-2 col-form-label"><%= f.label :password%></div>
          <div class="col-sm-8">
            <%= f.password_field :password, class: "form-control", placeholder: "Enter password", autuofocus: true%>
          </div>
        </div> 
        <!--end of third--> 
            <br>
            <div class="form-group row">
            <div class="col-sm-12 center">
                <%= f.submit(@user.new_record? ? "Sign Up" : "Update your Account", class:"btn btn-primary btn-lg")%>
            </div>
        </div>

        <% end %>    
        <div class=" center col-xs-4 col-xs-offset-4">
            [ <%= link_to "Cancel request and return to articles listing", articles_path%> ]
        </div>
    </div>
</div>

app/views/users/edit.html.erb
<h1 align="center"> Edit your Account </h1>

<%= render 'form'%>

app/views/users/index.html.erb
<h1 align ="center"> All Alpha-Blogers </h1>
<div class="pagination-wrapper">
    <%= will_paginate @users%>
</div>
<% @users.each do |user|%>
    <ul class="listing">
        <div class="row ">
            <div class="card center col-md-4 col-md-offset-4">
                <li> <%= link_to gravatar_for(user), user_path(user)%></li>
                <li class="article-title"><%= link_to user.username, user_path(user)%></li>
                <li> <small> <%= pluralize(user.articles.count, "article") if user.articles%></small></li>
                <%=link_to "view profie", user, class: "btn btn-xs"%>
                <%if logged_in?%>
                    <% if user== current_user %>
                        <%= link_to "edit profile", edit_user_path(user), class: "btn btn-xs btn-primary"%>
                    <% end %>
                    <%if current_user.admin?%>
                    <%= link_to "Delete profile", user_path(user), class: "btn btn-xs btn-danger", method: :delete, data: {confirm: "Are you Sure you want to delete the user and all assocated Articles?"}%>
                    <%end%>
                <% end %>
            </div>
        </div>
    </ul>
<%end %>
<div class="pagination-wrapper">
    <%= will_paginate @users%>
</div>

app/views/users/new.html.erb
<h1 align="center"> Welcome to Alpha-blog </h1>
<%= render 'form'%>

app/views/users/show.html.erb
<h1 align="center"> Welcome to <%= @user.username%>'s page </h1>
<div class="row">
    <div class= "cal-sm-4 col-md-offset-4">
       <span class="custom-avatar"><%= gravatar_for @user, size:150%></span>
    </div>
</div>    

<h6 align="center"> <%= @user.username%>'s Articles<h6>
<div class="pagination-wrapper">
    <%= will_paginate @user_articles%>
</div>
<%= render 'articles/article', obj:@user_articles%>

<div class="pagination-wrapper">
    <%= will_paginate @user_articles%>
</div>